# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Reports.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cart_Tab(object):
    def setupUi(self, Cart_Tab):
        Cart_Tab.setObjectName("Cart_Tab")
        Cart_Tab.resize(1468, 856)
        Cart_Tab.setStyleSheet("background-color:#fff;")
        self.gridLayout_4 = QtWidgets.QGridLayout(Cart_Tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.search_button = QtWidgets.QPushButton(Cart_Tab)
        self.search_button.setMinimumSize(QtCore.QSize(50, 50))
        self.search_button.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.search_button.setFont(font)
        self.search_button.setMouseTracking(True)
        self.search_button.setTabletTracking(True)
        self.search_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search_button.setStyleSheet("QPushButton {\n"
" background-color: #f6f4f4;\n"
"border-radius:25px;\n"
"color:black;\n"
";\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #81cdc6;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"color:#fff;\n"
"}\n"
"\n"
"shoppingbag:hover{\n"
"color:#fff;\n"
"background-repeat:no-repeat;\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.search_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/search/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon)
        self.search_button.setIconSize(QtCore.QSize(20, 20))
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.search_input = QtWidgets.QLineEdit(Cart_Tab)
        self.search_input.setMinimumSize(QtCore.QSize(300, 50))
        self.search_input.setMaximumSize(QtCore.QSize(600, 75))
        self.search_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search_input.setStyleSheet("border-radius:25px;\n"
"padding-right:10px;\n"
"padding-left:10px;\n"
"background-color:#f6f4f4;\n"
"")
        self.search_input.setText("")
        self.search_input.setCursorPosition(0)
        self.search_input.setDragEnabled(False)
        self.search_input.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_2.addWidget(self.search_input)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Cart_Tab)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"   border: 1px solid gray;\n"
"background-color:81cdc6;\n"
"}\n"
"QTabBar::tab {\n"
"  background: #81cdc6;\n"
"  color: #fff;\n"
"  padding: 10px;\n"
"border-radius: 20px;\n"
"\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #66b3a8 ;\n"
" }\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.Transactions = QtWidgets.QWidget()
        self.Transactions.setObjectName("Transactions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Transactions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Transactions)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(16)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(15, item)
        self.verticalLayout.addWidget(self.tableWidget_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(200, -1, 200, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.return_button = QtWidgets.QPushButton(self.Transactions)
        self.return_button.setMinimumSize(QtCore.QSize(175, 50))
        self.return_button.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.return_button.setFont(font)
        self.return_button.setMouseTracking(True)
        self.return_button.setTabletTracking(True)
        self.return_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.return_button.setStyleSheet("QPushButton {\n"
" background-color: #F88379;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #E5676B;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/Shop/Shoppingcart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_button.setIcon(icon1)
        self.return_button.setIconSize(QtCore.QSize(22, 22))
        self.return_button.setObjectName("return_button")
        self.horizontalLayout.addWidget(self.return_button)
        self.flag_transaction_button = QtWidgets.QPushButton(self.Transactions)
        self.flag_transaction_button.setMinimumSize(QtCore.QSize(175, 50))
        self.flag_transaction_button.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.flag_transaction_button.setFont(font)
        self.flag_transaction_button.setMouseTracking(True)
        self.flag_transaction_button.setTabletTracking(True)
        self.flag_transaction_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.flag_transaction_button.setStyleSheet("QPushButton {\n"
" background-color: #10cc94;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #0a9c73;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.flag_transaction_button.setIcon(icon1)
        self.flag_transaction_button.setIconSize(QtCore.QSize(22, 22))
        self.flag_transaction_button.setObjectName("flag_transaction_button")
        self.horizontalLayout.addWidget(self.flag_transaction_button)
        self.receipt_button = QtWidgets.QPushButton(self.Transactions)
        self.receipt_button.setMinimumSize(QtCore.QSize(175, 50))
        self.receipt_button.setMaximumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.receipt_button.setFont(font)
        self.receipt_button.setMouseTracking(True)
        self.receipt_button.setTabletTracking(True)
        self.receipt_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.receipt_button.setStyleSheet("QPushButton {\n"
" background-color: #10cc94;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #0a9c73;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.receipt_button.setIcon(icon1)
        self.receipt_button.setIconSize(QtCore.QSize(22, 22))
        self.receipt_button.setObjectName("receipt_button")
        self.horizontalLayout.addWidget(self.receipt_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.Transactions, "")
        self.Returns = QtWidgets.QWidget()
        self.Returns.setObjectName("Returns")
        self.gridLayout = QtWidgets.QGridLayout(self.Returns)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Returns)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(9)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.tableWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Returns, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Cart_Tab)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Cart_Tab)

    def retranslateUi(self, Cart_Tab):
        _translate = QtCore.QCoreApplication.translate
        Cart_Tab.setWindowTitle(_translate("Cart_Tab", "Cart"))
        self.search_input.setPlaceholderText(_translate("Cart_Tab", "  Search..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cart_Tab", "Log ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cart_Tab", "User ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Cart_Tab", "Action"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Cart_Tab", "Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Cart_Tab", "Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Cart_Tab", "User Logs"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Cart_Tab", "Total Amount"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Cart_Tab", "Price"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Cart_Tab", "Quantity"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Cart_Tab", "Customer"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Cart_Tab", "Product"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Cart_Tab", "Brand"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Cart_Tab", "Variation"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Cart_Tab", "Size"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Cart_Tab", "Category"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("Cart_Tab", "Time"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("Cart_Tab", "Date"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("Cart_Tab", "Type"))
        item = self.tableWidget_2.horizontalHeaderItem(12)
        item.setText(_translate("Cart_Tab", "User ID"))
        item = self.tableWidget_2.horizontalHeaderItem(13)
        item.setText(_translate("Cart_Tab", "Cashier"))
        item = self.tableWidget_2.horizontalHeaderItem(14)
        item.setText(_translate("Cart_Tab", "Payment ID"))
        item = self.tableWidget_2.horizontalHeaderItem(15)
        item.setText(_translate("Cart_Tab", "Contact"))
        self.return_button.setText(_translate("Cart_Tab", "Return Item"))
        self.flag_transaction_button.setText(_translate("Cart_Tab", "Flag Transaction"))
        self.receipt_button.setText(_translate("Cart_Tab", "Generate Receipt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Transactions), _translate("Cart_Tab", "Transactions"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Cart_Tab", "Return ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Cart_Tab", "Product Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("Cart_Tab", "Brand"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("Cart_Tab", "Variation"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("Cart_Tab", "Size"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("Cart_Tab", "Quantity"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("Cart_Tab", "Date"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("Cart_Tab", "Date of Return"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("Cart_Tab", "Transaction ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Returns), _translate("Cart_Tab", "Returns"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cart_Tab = QtWidgets.QWidget()
    ui = Ui_Cart_Tab()
    ui.setupUi(Cart_Tab)
    Cart_Tab.show()
    sys.exit(app.exec_())
