# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutUs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1255, 843)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("background-color:#fff;")
        self.gridLayout_8 = QtWidgets.QGridLayout(Form)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("background-color:#81cdc6;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color:#fff;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(1221, 601))
        self.widget.setMaximumSize(QtCore.QSize(1221, 601))
        self.widget.setStyleSheet("background-color:#f7f7f7 ;\n"
" border-style: solid;\n"
"    border-color: #dcdcdc;\n"
"    border-width: 1px;\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(15, 50, 15, 15)
        self.gridLayout_6.setHorizontalSpacing(30)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_4.setStyleSheet("background-color:#81cdc6;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"color:#fff;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_6.setStyleSheet("background-color:#81cdc6;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border:none;\n"
"color:#fff;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_6, 0, 1, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_7.setStyleSheet("background-color:#81cdc6;\n"
"border-top-left-radius: 20px;\n"
"border-top-right-radius: 20px;")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;\n"
"color:#fff;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_7, 0, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setStyleSheet("background-color:#fff;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 25, 5, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:none;")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_3 = QtWidgets.QFrame(self.widget_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border:none;\n"
"background-color:#fff;")
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:none;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("border:none;\n"
"background-color:#fff;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setStyleSheet("background-color:#fff;\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(10, 20, -1, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border:none;\n"
"background-color:#fff;\n"
"")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.gridLayout_11.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_5)
        self.label_42.setStyleSheet("border:none;")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.gridLayout_11.addWidget(self.label_42, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 1, 1, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.widget)
        self.widget_12.setStyleSheet("background-color:#fff;\n"
"")
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.widget_12)
        self.label_17.setMinimumSize(QtCore.QSize(200, 150))
        self.label_17.setMaximumSize(QtCore.QSize(200, 150))
        self.label_17.setStyleSheet("border:none;\n"
"image: url(:/Gab/gab-removebg-preview.png);\n"
"image: url(:/Gab/gab-removebg-preview.png);\n"
"background-color:#fff;\n"
"border-radius:65px;\n"
"")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border:none;\n"
"background-color:#fff;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border:none;\n"
"background-color:#fff;\n"
"color:gray;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.widget_12)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_21 = QtWidgets.QLabel(self.widget_12)
        self.label_21.setMinimumSize(QtCore.QSize(185, 150))
        self.label_21.setMaximumSize(QtCore.QSize(185, 150))
        self.label_21.setStyleSheet("border:none;\n"
"background-color:#fff;\n"
"image: url(:/Yohan/yohan-removebg-preview.png);\n"
"border-radius:65px;\n"
"")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_3.addWidget(self.label_21)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border:none;\n"
"background-color:#fff;")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.label_18 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border:none;\n"
"background-color:#fff;\n"
"color:gray;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.widget_12)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_20 = QtWidgets.QLabel(self.widget_12)
        self.label_20.setMinimumSize(QtCore.QSize(200, 150))
        self.label_20.setMaximumSize(QtCore.QSize(200, 150))
        self.label_20.setStyleSheet("border:none;\n"
"image: url(:/Tan/tan-removebg-preview.png);\n"
"background-color:#fff;\n"
"border-radius:65px;\n"
"")
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border:none;\n"
"background-color:#fff;")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border:none;\n"
"background-color:#fff;\n"
"color:gray;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.gridLayout_10.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_12, 1, 2, 1, 1)
        self.gridLayout_7.addWidget(self.widget, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "About Us"))
        self.label.setText(_translate("Form", "Store Information"))
        self.label_3.setText(_translate("Form", "System Information"))
        self.label_4.setText(_translate("Form", "Team"))
        self.label_5.setText(_translate("Form", "Located in Cainta Rizal, Jewell 7\n"
"Hardware is your go-to destination for\n"
"all your hardware needs "))
        self.label_8.setText(_translate("Form", "        Contacts:"))
        self.label_10.setText(_translate("Form", "0985-2434838"))
        self.label_9.setText(_translate("Form", "0953-0330697\n"
""))
        self.label_11.setText(_translate("Form", "A product management system with\n"
"point-of sale designed for Jewell 7 \n"
"Hardware,  developed using the Python\n"
"programming language and SQLite\n"
"database.\n"
"\n"
"This system includes features for\n"
"managing stocks, processing transactions\n"
"(Point of Sale), generating reports, and\n"
"performing analytics. It also uses Linear\n"
"Regression algorithm for predicting\n"
"sales within a weekly timeframe."))
        self.label_13.setText(_translate("Form", "Buenaventura, John Gabriel N."))
        self.label_14.setText(_translate("Form", "Frontend Developer"))
        self.label_15.setText(_translate("Form", "    Santos, Johan D."))
        self.label_18.setText(_translate("Form", " Full-stack Developer"))
        self.label_16.setText(_translate("Form", "Tan, Jose Mari V."))
        self.label_19.setText(_translate("Form", "Full-stack Developer"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
