# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffRegistration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_staffRegistration(object):
    def setupUi(self, staffRegistration):
        staffRegistration.setObjectName("staffRegistration")
        staffRegistration.resize(1218, 820)
        staffRegistration.setStyleSheet("background-color: #FCFEFE;")
        staffRegistration.setAnimated(True)
        staffRegistration.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(staffRegistration)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(500, 600))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: #81cdc6;\n"
" border-style: solid;\n"
"    border-color: black;\n"
"    border-width: 1px;\n"
"\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.logo = QtWidgets.QLabel(self.widget_2)
        self.logo.setMinimumSize(QtCore.QSize(420, 50))
        self.logo.setMaximumSize(QtCore.QSize(450, 290))
        self.logo.setStyleSheet("image: url(:/images/received_836614531712349.png);\n"
"\n"
"border:none;")
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.whiteContainer = QtWidgets.QWidget(self.centralwidget)
        self.whiteContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.whiteContainer.setMaximumSize(QtCore.QSize(500, 600))
        self.whiteContainer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.whiteContainer.setAutoFillBackground(False)
        self.whiteContainer.setStyleSheet("QWidget {\n"
"    background-color: #fff;\n"
" border-style: solid;\n"
"    border-color: black;\n"
"    border-width: 1px;\n"
"}")
        self.whiteContainer.setInputMethodHints(QtCore.Qt.ImhNone)
        self.whiteContainer.setObjectName("whiteContainer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.whiteContainer)
        self.gridLayout_2.setContentsMargins(45, 15, 45, 50)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.backButton = QtWidgets.QPushButton(self.whiteContainer)
        self.backButton.setMinimumSize(QtCore.QSize(0, 0))
        self.backButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color:#3d3d3d    ;\n"
"    padding: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #265C42;\n"
"}\n"
"")
        self.backButton.setIconSize(QtCore.QSize(16, 16))
        self.backButton.setFlat(True)
        self.backButton.setObjectName("backButton")
        self.gridLayout_2.addWidget(self.backButton, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(60)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.show_password_checkbox = QtWidgets.QCheckBox(self.whiteContainer)
        self.show_password_checkbox.setMinimumSize(QtCore.QSize(150, 0))
        self.show_password_checkbox.setMaximumSize(QtCore.QSize(500, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.show_password_checkbox.setFont(font)
        self.show_password_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.show_password_checkbox.setStyleSheet("border-color:white;\n"
"")
        self.show_password_checkbox.setObjectName("show_password_checkbox")
        self.horizontalLayout_2.addWidget(self.show_password_checkbox)
        self.setBirthdate_label = QtWidgets.QLabel(self.whiteContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setBirthdate_label.sizePolicy().hasHeightForWidth())
        self.setBirthdate_label.setSizePolicy(sizePolicy)
        self.setBirthdate_label.setMinimumSize(QtCore.QSize(150, 0))
        self.setBirthdate_label.setMaximumSize(QtCore.QSize(500, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.setBirthdate_label.setFont(font)
        self.setBirthdate_label.setStyleSheet("QLabel {\n"
"  background-color: #fff;\n"
"  padding: 4px;\n"
"  border: none;\n"
"  border-radius: 12px; /* Adjusted border-radius */\n"
"  position: relative;\n"
"  z-index: 0; /* We force a stacking context */\n"
"  color: black;\n"
"}\n"
"")
        self.setBirthdate_label.setLineWidth(0)
        self.setBirthdate_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.setBirthdate_label.setIndent(0)
        self.setBirthdate_label.setObjectName("setBirthdate_label")
        self.horizontalLayout_2.addWidget(self.setBirthdate_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.username_input = QtWidgets.QLineEdit(self.whiteContainer)
        self.username_input.setMinimumSize(QtCore.QSize(150, 55))
        self.username_input.setMaximumSize(QtCore.QSize(500, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("\n"
"QLineEdit {\n"
"  background-color: #c6c6c8;\n"
"  padding: 4px;\n"
"  border: none;\n"
"border-radius:12px;\n"
"  position: relative;\n"
"  z-index: 0; /* We force a stacking context */\n"
"}\n"
"")
        self.username_input.setText("")
        self.username_input.setFrame(True)
        self.username_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_input.setObjectName("username_input")
        self.gridLayout_2.addWidget(self.username_input, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password_input = QtWidgets.QLineEdit(self.whiteContainer)
        self.password_input.setMinimumSize(QtCore.QSize(150, 55))
        self.password_input.setMaximumSize(QtCore.QSize(500, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("\n"
"QLineEdit {\n"
"  background-color: #c6c6c8;\n"
"  padding:4px;\n"
"  border: none;\n"
"border-radius:10px;\n"
"\n"
"  position: relative;\n"
"  z-index: 0; /* We force a stacking context */\n"
"}\n"
"\n"
"QLineEdit::before {\n"
"  content: \"\";\n"
"  position: absolute;\n"
"  z-index: -2;\n"
"  inset: -5px;\n"
"  transform: translate(10px, 8px);\n"
"  background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop: 0 rgb(198,198,200), stop: 1 rgb(204,204,206));\n"
"  filter: blur(10px);\n"
"}\n"
"\n"
"QLineEdit::after {\n"
"  content: \"\";\n"
"  position: absolute;\n"
"  z-index: -1;\n"
"  inset: 0;\n"
"  background: inherit;\n"
"  border: inherit;\n"
"  box-shadow: inherit;\n"
"}")
        self.password_input.setText("")
        self.password_input.setFrame(True)
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.horizontalLayout.addWidget(self.password_input)
        self.birthdate_edit = QtWidgets.QDateEdit(self.whiteContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birthdate_edit.sizePolicy().hasHeightForWidth())
        self.birthdate_edit.setSizePolicy(sizePolicy)
        self.birthdate_edit.setMinimumSize(QtCore.QSize(150, 55))
        self.birthdate_edit.setMaximumSize(QtCore.QSize(500, 55))
        self.birthdate_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.birthdate_edit.setStyleSheet("\n"
"QDateEdit {\n"
"  background-color: #c6c6c8;\n"
"  padding: 4px;\n"
"  border: none;\n"
"border-radius:12px;\n"
"  position: relative;\n"
"  z-index: 0; /* We force a stacking context */\n"
"color:#636364;\n"
"}\n"
"")
        self.birthdate_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.birthdate_edit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.birthdate_edit.setSpecialValueText("")
        self.birthdate_edit.setCalendarPopup(True)
        self.birthdate_edit.setObjectName("birthdate_edit")
        self.horizontalLayout.addWidget(self.birthdate_edit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.firstName_input = QtWidgets.QLineEdit(self.whiteContainer)
        self.firstName_input.setMinimumSize(QtCore.QSize(150, 55))
        self.firstName_input.setMaximumSize(QtCore.QSize(500, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.firstName_input.setFont(font)
        self.firstName_input.setStyleSheet("\n"
"QLineEdit {\n"
"  background-color: #c6c6c8;\n"
"  padding: 4px;\n"
"  border: none;\n"
"border-radius:12px;\n"
"  position: relative;\n"
"  z-index: 0; /* We force a stacking context */\n"
"}\n"
"")
        self.firstName_input.setText("")
        self.firstName_input.setFrame(True)
        self.firstName_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.firstName_input.setObjectName("firstName_input")
        self.gridLayout_2.addWidget(self.firstName_input, 2, 0, 1, 1)
        self.lastName_input = QtWidgets.QLineEdit(self.whiteContainer)
        self.lastName_input.setMinimumSize(QtCore.QSize(150, 55))
        self.lastName_input.setMaximumSize(QtCore.QSize(500, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.lastName_input.setFont(font)
        self.lastName_input.setStyleSheet("\n"
"QLineEdit {\n"
"  background-color: #c6c6c8;\n"
"  padding: 4px;\n"
"  border: none;\n"
"border-radius:12px;\n"
"  position: relative;\n"
"  z-index: 0; /* We force a stacking context */\n"
"}\n"
"")
        self.lastName_input.setText("")
        self.lastName_input.setFrame(True)
        self.lastName_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lastName_input.setObjectName("lastName_input")
        self.gridLayout_2.addWidget(self.lastName_input, 3, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.whiteContainer)
        self.clearButton.setMinimumSize(QtCore.QSize(150, 50))
        self.clearButton.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.clearButton.setFont(font)
        self.clearButton.setMouseTracking(True)
        self.clearButton.setTabletTracking(True)
        self.clearButton.setStyleSheet("QPushButton {\n"
" background-color: #F88379;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #F66150;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_2.addWidget(self.clearButton, 9, 0, 1, 1)
        self.registerButton = QtWidgets.QPushButton(self.whiteContainer)
        self.registerButton.setMinimumSize(QtCore.QSize(150, 50))
        self.registerButton.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.registerButton.setFont(font)
        self.registerButton.setMouseTracking(True)
        self.registerButton.setTabletTracking(True)
        self.registerButton.setStyleSheet("QPushButton {\n"
" background-color: #10cc94;\n"
"border-radius:12px;\n"
"color:#fff;\n"
"}\n"
"QPushButton#quit_button {\n"
"   background-color: green;\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: #fff;\n"
"}\n"
"QpushButton{\n"
"border: 2px solid #555;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"border-width:200px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #0a9c73;\n"
"   transition: background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"border:none;\n"
"")
        self.registerButton.setObjectName("registerButton")
        self.gridLayout_2.addWidget(self.registerButton, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.whiteContainer, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        staffRegistration.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(staffRegistration)
        self.statusbar.setObjectName("statusbar")
        staffRegistration.setStatusBar(self.statusbar)

        self.retranslateUi(staffRegistration)
        QtCore.QMetaObject.connectSlotsByName(staffRegistration)

    def retranslateUi(self, staffRegistration):
        _translate = QtCore.QCoreApplication.translate
        staffRegistration.setWindowTitle(_translate("staffRegistration", "staffRegistration"))
        self.backButton.setText(_translate("staffRegistration", "←"))
        self.show_password_checkbox.setText(_translate("staffRegistration", "Show Password"))
        self.setBirthdate_label.setText(_translate("staffRegistration", "Set Birthdate"))
        self.username_input.setPlaceholderText(_translate("staffRegistration", "Username"))
        self.password_input.setPlaceholderText(_translate("staffRegistration", "Password"))
        self.firstName_input.setPlaceholderText(_translate("staffRegistration", "First Name"))
        self.lastName_input.setPlaceholderText(_translate("staffRegistration", "Last Name"))
        self.clearButton.setText(_translate("staffRegistration", "Clear"))
        self.registerButton.setText(_translate("staffRegistration", "Register"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    staffRegistration = QtWidgets.QMainWindow()
    ui = Ui_staffRegistration()
    ui.setupUi(staffRegistration)
    staffRegistration.show()
    sys.exit(app.exec_())
